package com.gcu.ecommerce.controllers;

import javax.servlet.http.HttpSession;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;

import com.gcu.ecommerce.business.ProductBusinessService;
import com.gcu.ecommerce.models.ProductModel;
import org.springframework.web.bind.annotation.PathVariable; // Milestone 5

/**
 * Spring Framework Controller class for handling requests to the product pages and api endpoints.
 */
@Controller
public class ProductController {

    private final ProductBusinessService productBusinessService;

    /**
     * Business service dependency injected through the constructor. This allows the controller to utilize the business service's methods to perform operations related to products.
     *
     * @param productBusinessService injected product service bean
     */
    public ProductController(ProductBusinessService productBusinessService) {
        this.productBusinessService = productBusinessService;
    }
    
    /**
     * Handles requests to the "/products" url. Checks for a logged-in user in the session and redirects to login if not found. If logged in, retrieves the list of products from the business service and adds it to the model for rendering the products view. 
     *
     * @param model The model to which the list of products will be added.
     * @param session The HTTP session used to check for a logged-in user.
     * @return The name of the view to be rendered, in this case "products", or a redirect to the login page if the user is not logged in.
     */

    @GetMapping("/products")
    public String products(Model model, HttpSession session) {

        if (session.getAttribute("loggedInUser") == null) {
            return "redirect:/login";
        }

        model.addAttribute("products", productBusinessService.getProducts());
        return "products";
    }
    
    /**
     * Handles requests to the "/products/create" url. Checks for a logged-in user in the session and redirects to login if not found. If logged in, prepares the create-product form by adding a new ProductModel instance to the model.

     * @param model The model to which the form attributes will be added.
     * @param session The HTTP session used to check for a logged-in user.
     * @return The name of the view to be rendered, in this case "create-product", or a redirect to the login page if the user is not logged in.
     */

    @GetMapping("/products/create")
    public String createProductForm(Model model, HttpSession session) {

        if (session.getAttribute("loggedInUser") == null) {
            return "redirect:/login";
        }

        model.addAttribute("productModel", new ProductModel());
        return "create-product";
        
        
    }
    
    /**
     * Handles post requests to the "/products/create" url, as generated by the create-product form. Checks for a logged-in user in the session and redirects to login if not found. If logged in, Redirects back to the create-product form if product information is invalid. Redirects to the products list if successful.
     *
     * @param productModel The inputted form information for the new product.
     * @param result The result of validating the productModel input.
     * @param model The model to which form attributes may be added in case of validation errors.
     * @param session The HTTP session used to check for a logged-in user.
     * @return The name of the view to be rendered, either "create-product" if validation fails, or a redirect to the products list if successful.
     */

    @PostMapping("/products/create")
    public String createProduct(@Valid ProductModel productModel, BindingResult result, Model model, HttpSession session) {

        System.out.println("POST /products/create reached.");

        if (session.getAttribute("loggedInUser") == null) {
            System.out.println("User not logged in.");
            return "redirect:/login";
        }

        if (result.hasErrors()) {
            System.out.println("Validation failed.");
            return "create-product";
        }

        System.out.println("Saving product: " + productModel.getName());

        productBusinessService.addProduct(productModel);
        return "redirect:/products";
    }

    /**
     * Handles post requests to the "/products/create/{id}" url. The {id} path variable determines which product's info will be fetched.
     *
     * @param id The ID of the product to retrieve the details of
     * @param model The model to which the product details will be added
     * @param session The HTTP session used to check for a logged-in user
     * @return The name of the view to be rendered, in this case "product-details", or a redirect to the login page if the user is not logged in.
     */
    @GetMapping("/products/details/{id}")
    public String productDetails(@PathVariable int id, Model model, HttpSession session) {

        if (session.getAttribute("loggedInUser") == null) {
            return "redirect:/login";
        }

        model.addAttribute("product", productBusinessService.getProductById(id));
        return "product-details";
    }

    
    /**
     * Handles get requests to the "/products/edit/{id}" url. Opens a form for editing a product. The {id} path variable determines which product will be fetched for editing
     *
     * @param id The ID of the product to be edited.
     * @param model The model to which the product details will be added for the edit form.
     * @param session The HTTP session used to check for a logged-in user.
     * @return The name of the view to be rendered, in this case "edit-product", or a redirect to the login page if the user is not logged in.
     */
    
    @GetMapping("/products/edit/{id}")
    public String editProductForm(@PathVariable int id, Model model, HttpSession session) {

        if (session.getAttribute("loggedInUser") == null) {
            return "redirect:/login";
        }

        model.addAttribute("productModel", productBusinessService.getProductById(id));
        return "edit-product";
    }

    
    /**
     * Handles post requests to the "/products/update" url, as generated by the edit-product form, to edit product details. Checks for a logged-in user in the session and redirects to login if not found. If validation fails, redirects back to the edit-product form. If successful, updates the product and redirects to the products list.

     * @param productModel The updated product data submitted from the edit form.
     * @param result The result of validating the productModel input.
     * @param session The HTTP session used to check for a logged-in user.
     * @return The name of the view to be rendered, either "edit-product" if validation fails, or a redirect to the products list if successful.
     */
    
    @PostMapping("/products/update")
    public String updateProduct(@Valid ProductModel productModel, BindingResult result, HttpSession session) {

        if (session.getAttribute("loggedInUser") == null) {
            return "redirect:/login";
        }

        if (result.hasErrors()) {
            return "edit-product";
        }

        productBusinessService.updateProduct(productModel);
        return "redirect:/products";
    }
    
    /**
     * Handles get requests to the "/products/delete/{id}" url. Deletes the specified product. Checks for a logged-in user in the session and redirects to login if not found. If successful, deletes the product and redirects to the products list.

     * @param id The ID of the product to be deleted.
     * @param session The HTTP session used to check for a logged-in user.
     * @return A redirect to the products list if successful, or to the login page if the user is not logged in.
     */
    @GetMapping("/products/delete/{id}")
    public String deleteProduct(@PathVariable int id, HttpSession session) {

        if (session.getAttribute("loggedInUser") == null) {
            return "redirect:/login";
        }

        productBusinessService.deleteProduct(id);
        return "redirect:/products";
    }
}